services:
  - type: redis
    name: sidekiq-redis
    region: singapore
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-worker
    env: ruby
    region: singapore
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
