default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL") { nil } %>

test:
  <<: *default
  database: naibus_test

development:
  <<: *default
  database: naibus_development

production:
  <<: *default
